[MS-82] 거점 좋아요
MODU-TAXI/server-api pull request #29
Opened 2024-04-18 19:03 UTC by jaewonLeeKOR

## 요약 🎀
- 거점 좋아요 구현

## 상세 내용 🌈
- 거점 좋아요 엔티티 이름 변경
  - memberspot -> likedSpot
- 즐겨찾기 생성
- 즐겨찾기 제거
- 즐겨찾기 목록 조회 (페이징)
- 기존의 거점 조회 API 에 즐겨찾기 반환 추가

## 질문 및 이외 사항 🚩
- 현재 `figma`에 사용되고 있는 의도대로만 구현하였습니다.
- 구현한 API 각각 사용자 조회를 제회하고 1개의 쿼리만 발생하는것을 확인했습니다.

2024-04-20 07:29 UTC, tjdgns8439 approved these changes, later dismissed
LGTM

2024-04-20 07:29 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/domain/likedSpot/dao/LikedSpotMysqlResponse.java
> +        Point getSpotpoint();
건설적인 리뷰는 아니지만 point부분이 카멜케이스가 아닌 것이 아주 약간 신경이 쓰입니다..ㅎ.ㅎ 다음 pr 때 반영해주세여

2024-04-20 07:29 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/domain/likedSpot/service/RegisterLikedSpotService.java
> +        LikedSpot likedSpot = LikedSpot.toEntity(spot, member);
이 역시 건설적인 리뷰는 아니지만 반환된 객체가 필요없다면 한 줄로 합쳐도 될 것 같습니다!

2024-04-20 07:29 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/domain/likedSpot/dto/LikedSpotResponseDto.java
> +    public static class LikedSpotListResponse {
List에 사용되는 Response객체이기에 Dto명에 List를 삽입하는 부분에 대해서는 회의할 때 컨벤션을 정의해볼까요?

2024-04-20 07:50 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/likedSpot/dao/LikedSpotMysqlResponse.java
> +        Point getSpotpoint();
이건 거점에서도 이렇게 해놨어서 통일한건데 다음에 바꾸는게 낫겠네요

2024-04-20 07:58 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/likedSpot/service/RegisterLikedSpotService.java
> +        LikedSpot likedSpot = LikedSpot.toEntity(spot, member);
`toEntity` 메서드를 사용하며 `LikedSpot` 객체가 메모리에 할당되고 여기 서비스 메서드에서는 Shallow Cpoy로 새롭게 메모리에 할당되지는 않을것으로 생각되어 메모리 누수 문제는 없을거 같습니다.
이 또한 코드 스타일에 대해 얘기 해보는게 좋을것 같아요.
저는 해당 객체를 사용하고 있다는것을 명시해주고 싶어서 사용했습니다.
또한 저는 메서드의 argument 내에서 메서드를 재사용하는 스타일은 코드 가독성이 안좋아진다고 생각하여 지양하기도 합니다.

2024-04-20 07:58 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/likedSpot/dto/LikedSpotResponseDto.java
> +    public static class LikedSpotListResponse {
네 이부분은 다음 서버 회의에서 정하면 좋겠네요!

2024-04-20 10:56 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/likedSpot/dao/LikedSpotMysqlResponse.java
> +        Point getSpotpoint();
변경 완료했습니다!

2024-04-20 18:59 UTC, YooJisu826 requested changes
고생하셨습니다! 코멘트 하나만 확인해주세요 :D

2024-04-20 18:59 UTC, YooJisu826 commented on src/main/java/com/modutaxi/api/domain/likedSpot/entity/LikedSpot.java
>              .build();
toEntity는 Entity에 작성하시는군요.. 전 지금까지 Mapper에 작성했는데 이것도 통일해야할 거 강습니당

2024-04-20 18:59 UTC, YooJisu826 commented on src/main/java/com/modutaxi/api/domain/likedSpot/controller/GetLikedSpotController.java
> +    public ResponseEntity<PageResponseDto<List<LikedSpotListResponse>>> getLikedSpotList(@Parameter(description = "조회할 page") @RequestParam int page, @Parameter(description = "조회할 page 단위") @RequestP
이 API에는 memberId 받는게 없는 것 같은데 어떻게 조회하나요??

2024-04-20 19:09 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/likedSpot/entity/LikedSpot.java
>              .build();
저도 Mapper를 이용해서 사용했는데 toEntity가 이미 정의되어 있어 새로 정의하지 않고 사용하였습니다.
회의에서 얘기 해야겠네요.

2024-04-20 19:10 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/likedSpot/controller/GetLikedSpotController.java
> +    public ResponseEntity<PageResponseDto<List<LikedSpotListResponse>>> getLikedSpotList(@Parameter(description = "조회할 page") @RequestParam int page, @Parameter(description = "조회할 page 단위") @RequestP
어..? 그러네요.. 😓
수정하겠습니다.

2024-04-21 09:40 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/likedSpot/dto/LikedSpotResponseDto.java
> +    public static class LikedSpotListResponse {
이미 `List` 가 dto에 들어가있긴한데 `LikedSpotResponseList` 와 같은 형식을 얘기하신건가요?
저는 dto에 리스트가 들어있는것이 아니라 리스트형태로 반환될 반환 dto라는것을 명시하려고 이렇게 작성했습니다.
PageResponseDto에 `List`를 미리 넣어둔 방식이 아니라 List를 함께 제네릭으로 넣어주는 방식으로 구현되어있기도 합니다.
이점에서 `PageResponseDto` 의 result의 타입을 `List<T>` 로 바꾼다면 컨트롤러의 반환 타입이 더 가독성이 좋아질거라고 생각합니다.
현재는 `ResponseEntity<PageResponseDto<List<LikedSpotListResponse>>>` 와 같이 정의가 되는데 이 방식을 적용하면 `ResponseEntity<PageResponseDto<LikedSpotListResponse>>`으로 바뀔것입니다.
어떤가요?

2024-04-21 09:54 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/likedSpot/controller/GetLikedSpotController.java
> +    public ResponseEntity<PageResponseDto<List<LikedSpotListResponse>>> getLikedSpotList(@Parameter(description = "조회할 page") @RequestParam int page, @Parameter(description = "조회할 page 단위") @RequestP
수정 완료했습니다!

2024-04-21 09:54 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/likedSpot/service/RegisterLikedSpotService.java
> +        LikedSpot likedSpot = LikedSpot.toEntity(spot, member);
수정 완료했습니다!

2024-04-21 12:07 UTC, YooJisu826 approved these changes
LGTM 👍

2024-04-21 12:21 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/domain/likedSpot/dto/LikedSpotResponseDto.java
> +    public static class LikedSpotListResponse {
해당 방식을 적용해 후자처럼 표현되면 더 좋을 것 같습니다!

2024-04-21 12:22 UTC, tjdgns8439 approved these changes

2024-04-21 15:10 UTC, merged