[MS-88] 반경 내 모집방 조회
MODU-TAXI/server-api pull request #30
Opened 2024-04-19 03:05 UTC by jaewonLeeKOR

## 요약 🎀
- 반경 내 모집방 좌표 조회 구현

## 상세 내용 🌈
- 모집방 위치 데이터 저장 엔티티 필드 변경
- 반경 내 모집방 조회 구현
  - 모집방 id, 좌표, 거점 이름 을 반환합니다.
    <img width="1216" alt="image" src="https://github.com/MODU-TAXI/server-api/assets/58386334/320df721-9c76-41f9-9235-dd9339a25d38">

2024-04-20 08:03 UTC, tjdgns8439 approved these changes
LGTM

2024-04-20 08:07 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/domain/room/controller/GetRoomController.java
> +    @PostMapping("/map")
리소스를 생성,변경하지 않고 단순 조회로직인데 왜 PostMapping을 사용하였는 지 궁금합니다

2024-04-20 08:29 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/controller/GetRoomController.java
> +    @PostMapping("/map")
아 조회라도 body로 데이터를 주고받기위해서 `POST`를 사용했습니다.
`GET`은 바디를 사용하지 않는 형식이라서요.

2024-04-20 19:26 UTC, YooJisu826 requested changes
고생하셨습니다 코멘트 한번만 확인 부탁드려요~!!

2024-04-20 19:26 UTC, YooJisu826 commented on src/main/java/com/modutaxi/api/domain/room/controller/GetRoomController.java
> +    @PostMapping("/map")
제 개인적인 생각이지만 x 좌표, y 좌표를 그냥 Param으로 받고 GET으로 사용하는게 더 좋을 것 같아요! 조회 API인데 POST를 쓰는게 REST하지 않은 거 같아서요ㅜㅜ

2024-04-20 19:37 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/controller/GetRoomController.java
> +    @PostMapping("/map")
두분 다 그렇게 생각한다면 Path Parameter 방식으로 바꾸는게 좋을것 같네요.
거점 조회에서도 사용했던 방식이라 이 방식에 동의한것으로 인지했습니다.
그럼 거점 조회에서도 동일하게 수정을 진행하도록 하겠습니다.

2024-04-21 12:11 UTC, YooJisu826 submitted a review, later dismissed
여기는 나중에 수정하시나여? 고생하셨어요!!

2024-04-21 15:04 UTC, tjdgns8439 submitted a review, later dismissed

2024-04-21 15:20 UTC, tjdgns8439 submitted a review, later dismissed

2024-04-21 15:51 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/controller/GetRoomController.java
> +    @PostMapping("/map")
GET 형식으로 바꿨습니다!!!!!!!!!

2024-04-21 15:53 UTC, tjdgns8439 submitted a review, later dismissed

2024-04-22 01:46 UTC, tjdgns8439 approved these changes
LGTM~!
다른 조회 응답의 depaturePoint도 x,y가 아닌 longitude, latitude로 변경한 부분 다음 PR에서 확인했습니다!

2024-04-22 04:33 UTC, YooJisu826 approved these changes
반영 굿굿👍👍👍

2024-04-22 05:33 UTC, merged