[MS-81] 모집방 목록 조회 필터 추가
MODU-TAXI/server-api pull request #31
Opened 2024-04-19 13:33 UTC by jaewonLeeKOR

## 요약 🎀
- 모집방 목록 조회 필터 추가

## 상세 내용 🌈
- 모집방 목록 조회 필터 추가
  - 마감임박 필터
    - PM 님과 얘기하여 시간 기준으로 현재시간보다 -10분 ~ 20분 범위의 모집방을 조회하도록 하였습니다.
  - 카테고리 필터
    - 남자만/여자만, 매너탑승, 조용히, 학생인증
  - 도착 거점 필터
    - 거점 id를 입력하요 필터링

## 질문 및 이외 사항 🚩
- 방 목록 조회와 맞지 않는 엔드포인트라 생각되어 `POST` `/api/rooms/list` 로 엔드포인트를 재구성하였습니다.
  <img width="1229" alt="image" src="https://github.com/MODU-TAXI/server-api/assets/58386334/e8da9ce3-73a1-40d7-8575-1e90ffcc14a3">

2024-04-19 13:33 UTC, jaewonLeeKOR commented
@MODU-TAXI/server-crew

2024-04-20 09:47 UTC, tjdgns8439 approved these changes, later dismissed
LGTM!

2024-04-20 09:47 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/domain/room/controller/GetRoomController.java
> +    @PostMapping("/list")
어떤 기준에서 Get보다는 Post가 맞다고 생각하셨나요?
저는 조회기능이기도 하고 캐싱의 관점에서 볼 때에도 Get 요청이 맞겠거니 생각했습니다..!!

2024-04-20 09:47 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/domain/room/entity/RoomTagBitMask.java
> +    ONLY_WOMAN,
지금은 개발 초기이기에 상관없지만 태그가 db에 저장되는 값은 int형이기 때문에 각별히 조심해야할 것 같습니다.
이에 따라 태그를 웬만하면 삭제하지 않고, 추가할 때 순서대로 추가하는 것이 좋을 것 같습니다!

2024-04-20 09:47 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/domain/room/entity/RoomTagBitMask.java
> +    ONLY_WOMAN,
이렇게 보니까 추가,삭제,변경에 있어 크게 확장성이 좋지는 않은 것 같기도 하네요..!

2024-04-20 09:47 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/domain/room/dto/RoomRequestDto.java
> +        @Schema(example = "[\"REGARDLESS_OF_GENDER\", \"STUDENT_CERTIFICATION\"]", description = "모집방 태그")
"REGARDLESS_OF_GENDER" 해당 태그는 삭제하신 것에 따라 예제에서도 변경해주시면 감사하겠습니다!

2024-04-20 10:43 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/entity/RoomTagBitMask.java
> +    ONLY_WOMAN,
이것도 회의를 통해 정해도록해요

2024-04-20 10:43 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/controller/GetRoomController.java
> +    @PostMapping("/list")
페이지 번호, 페이지 크기 찾으려는 거점 id, 마감임박, 모집방 태그를 엔드포인트 uri 만을 이용하여 받아오기에는 uri가 너무 난잡해진다고 생각하였습니다.
`GET`을 이용하여 데이터를 받아온다고 하였을때 다른 부분들은 바꿔도 좋지만 roomTag의 경우는 어떻게 받아오는것이 좋을까요?
리뷰 해주신것처럼 roomTag의 경우 정수값으로 저장되기 때문에 이를 프론트 단에서부터 받아오는것은 좋지 않은 인터페이스라고 생각했습니다.

2024-04-20 10:43 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/dto/RoomRequestDto.java
> +        @Schema(example = "[\"REGARDLESS_OF_GENDER\", \"STUDENT_CERTIFICATION\"]", description = "모집방 태그")
네 고치겠습니다!

2024-04-20 10:49 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/dto/RoomRequestDto.java
> +        @Schema(example = "[\"REGARDLESS_OF_GENDER\", \"STUDENT_CERTIFICATION\"]", description = "모집방 태그")
수정 완료했습니다!

2024-04-20 19:30 UTC, YooJisu826 commented on src/main/java/com/modutaxi/api/domain/room/controller/GetRoomController.java
> +    @PostMapping("/list")
저도 POST보다는 GET이 맞다고 생각합니다! 아무리 파람이 많아지더라도요! GET에서 파람으로 보낼 수 있는 글자수 제한이 2000자라고 하네요!! 그 전까진 괜찮지 않을까요~? 

그리고 이거 한번 참고해보시면 좋을 거 같습니당. 

https://bum752.github.io/posts/Spring-%EC%96%B4%ED%94%8C%EB%A6%AC%EC%BC%80%EC%9D%B4%EC%85%98%EC%97%90%EC%84%9C-Request-Parameter%EB%A5%BC-%EB%AA%A8%EB%8D%B8-%ED%81%B4%EB%9E%98%EC%8A%A4%EB%A1%9C-%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0/

2024-04-20 19:40 UTC, YooJisu826 requested changes
고생하셨고 리뷰 늦게 해서 죄송합니다 ㅠㅠ 코멘트 확인 부탁드립니다!

2024-04-20 19:40 UTC, YooJisu826 commented on src/main/java/com/modutaxi/api/domain/room/controller/GetRoomController.java
> +    @PostMapping("/list")
저도 POST보다는 GET이 맞다고 생각합니다! 아무리 파람이 많아지더라도요! GET에서 파람으로 보낼 수 있는 글자수 제한이 2000자라고 하네요!! 그 전까진 괜찮지 않을까요~? 

그리고 이거 한번 참고해보시면 좋을 거 같습니당. 

https://bum752.github.io/posts/Spring-%EC%96%B4%ED%94%8C%EB%A6%AC%EC%BC%80%EC%9D%B4%EC%85%98%EC%97%90%EC%84%9C-Request-Parameter%EB%A5%BC-%EB%AA%A8%EB%8D%B8-%ED%81%B4%EB%9E%98%EC%8A%A4%EB%A1%9C-%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0/

2024-04-20 19:40 UTC, YooJisu826 commented on src/main/java/com/modutaxi/api/domain/room/repository/RoomRepository.java
> +    Slice<Room> findAllWhereTagBitMaskAndSpotIdOrderByCreatedAtDesc(Long spotId, Integer tagBitMask, Pageable pageable);
`AND (:spotId IS NULL OR r.spotId <> :spotId)` 이 조건 넣어서 아래와 같이 작성하면

```
@Query("SELECT r FROM Room r WHERE BITAND(r.roomTagBitMask, :tagBitMask) = :tagBitMask AND r.roomStatus = 0 AND (:spotId IS NULL OR r.spotId <> :spotId) ORDER BY r.createdAt DESC")
    Slice<Room> findAllWhereTagBitMaskAndSpotIdOrderByCreatedAtDesc(Long spotId, Integer tagBitMask, Pageable pageable);
```

하나의 쿼리로 spotId가 있을 때 그리고 없을 때, 두 가지 기능을 합칠 수 있을 것 같습니다! (그래도 테스트는 해봐야할 듯 합니당)

2024-04-20 19:40 UTC, YooJisu826 commented on src/main/java/com/modutaxi/api/domain/room/service/GetRoomService.java
> +                return roomRepository.findAllWhereTagBitMaskAndSpotIdOrderByCreatedAtDesc(spotId, tagBitMask, pageable);
그럼 여기가 많이 줄어들 것 같아요~!!

2024-04-20 19:42 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/repository/RoomRepository.java
> +    Slice<Room> findAllWhereTagBitMaskAndSpotIdOrderByCreatedAtDesc(Long spotId, Integer tagBitMask, Pageable pageable);
네 두 메서드를 하나로 합쳐보겠습니다.!

2024-04-20 19:51 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/controller/GetRoomController.java
> +    @PostMapping("/list")
저도 REST 형식을 맞추는것이 맞고 그 방식을 좋아하는데요..
저번 이메일 요청, 인증 API도 그러한 방식으로 만들엇다가 프론트의 요청에따라 GET 방식에서 POST 방식으로 바꾼 선례가 있었습니다. 거긴 더 심각한게 파라미터 하나짜리 dto 거든요..
그런 이유로 연달아 올라온 PR들에 GET 방식을 채택하지 않고 POST를 사용했네요.
이부분도 한번 얘기 했으면 합니다.

2024-04-21 10:14 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/controller/GetRoomController.java
> +    @PostMapping("/list")
RESTful하게 수정 완료했습니다!

2024-04-21 10:31 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/repository/RoomRepository.java
> +    Slice<Room> findAllWhereTagBitMaskAndSpotIdOrderByCreatedAtDesc(Long spotId, Integer tagBitMask, Pageable pageable);
네 종류의 쿼리를 하나로 합쳤습니다!!

2024-04-21 10:31 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/service/GetRoomService.java
> +                return roomRepository.findAllWhereTagBitMaskAndSpotIdOrderByCreatedAtDesc(spotId, tagBitMask, pageable);
넵 덕분에 많이 줄였습니다~!!

2024-04-21 12:10 UTC, YooJisu826 approved these changes
고생하셨습니다!! 쿼리 한개로 줄이셨네요 ㄷㄷ

2024-04-21 15:04 UTC, tjdgns8439 approved these changes

2024-04-21 15:05 UTC, merged