[MS-98] 방 생성 예외처리
MODU-TAXI/server-api pull request #39
Opened 2024-04-23 09:35 UTC by tjdgns8439

## 요약 🎀
- 방 생성 예외처리
- RoomRequestDto의 description 필드 삭제

## 상세 내용 🌈
- Room을 생성할 때 검증해야할 요소가 많은 만큼 메서드를 분리하였습니다.
```java
private void createRoomRequestValidator(Member member, CreateRoomRequest createRoomRequest) {
        if (roomRepository.existsRoomByRoomManagerId(member.getId())) {
            throw new BaseException(RoomErrorCode.ALREADY_MEMBER_IS_MANAGER);
        }

        if (convertRoomTagListToBitMask(createRoomRequest.getRoomTagBitMask())
            == RoomTagBitMask.ONLY_WOMAN.getValue() + RoomTagBitMask.ONLY_MAN.getValue()) {
            throw new BaseException(RoomErrorCode.BOTH_GENDER);
        }

        if (createRoomRequest.getDepartureTime().isBefore(LocalDateTime.now())) {
            throw new BaseException(RoomErrorCode.DEPARTURE_BEFORE_CURRENT);
        }

        Float longitude = (float) createRoomRequest.getDeparturePoint().getX();
        Float latitude = (float) createRoomRequest.getDeparturePoint().getY();
        if (latitude < MIN_LATITUDE || latitude > MAX_LATITUDE
            || longitude < MIN_LONGITUDE || longitude > MAX_LONGITUDE) {
            throw new BaseException(RoomErrorCode.DEPARTURE_EXCEED_RANGE);
        }
    }
```

### 추가된 예외처리
**출발 위치가 대한민국의 범위를 벗어나는 상황에서 예외처리를 해주었습니다.**
- 아래 예시는 대한민국의 북위를 벗어난 북위 41도의 요청에 대한 예외처리입니다.
<img width="741" alt="스크린샷 2024-04-23 오후 6 14 13" src="https://github.com/MODU-TAXI/server-api/assets/100510247/2eadb769-de5d-40b4-8953-0679ef73ae90">

**방 생성 시간보다 출발 시간이 앞선 상황에서 예외처리를 해주었습니다.**
- 아래 예시는 요청 날짜 4/23일보다 앞선 4/22일에 출발하겠다는 요청에 대한 예외처리 예시입니다.
<img width="728" alt="스크린샷 2024-04-23 오후 6 14 40" src="https://github.com/MODU-TAXI/server-api/assets/100510247/76b82063-5789-4034-a7b5-a66ed3c892cc">

## 질문 및 이외 사항 🚩
- 시간과 출발 위치에 대한 예외처리는 보다 구체적인 기획이 결정되면 다시 조정할 예정입니다.

## 리뷰어에게 ✨
-

2024-04-23 12:24 UTC, jaewonLeeKOR requested changes
리뷰 확인해보시고 답변 부탁드립니다.

2024-04-23 12:24 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/dto/RoomResponseDto.java
>                  .duration(room.getDuration())
`dto`의 `toDto` 메서드의 사용에 대해서는 회의를 하며 얘기해보는게 좋을거 같아요.
저는 Constructor 형식으로 사용하고 있거든요. toDto을 사용할 시에는 dto 클래스에 메서드가 많이 생겨 가독성도 떨어질거 같기도 하고요.

2024-04-23 12:24 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/dto/RoomResponseDto.java
> +
이런거 사실 가끔 조금씩 불편할때가 있긴합니다 🫣
넘어가셔도 되요!

2024-04-23 12:24 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/service/RegisterRoomService.java
> +
`RoomMapper` 내에서 `Point` 객체를 만들어주는 로직이 존재하는데 중복적인 코드를 작성하신 이유가 있나요?

2024-04-23 12:24 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/service/UpdateRoomService.java
> +                : oldRoomData.getLatitude());
구글 코드스타일인가요?
저는 적용하면 이렇게 줄바꿈이 작용되지는 않던데.. 저는 줄바꿈이 너무 많아서 더 보기 힘든거 같아요.

2024-04-23 12:24 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/service/UpdateRoomService.java
>      public boolean shouldUpdateTaxiInfo(UpdateRoomRequest updateRoomRequest) {
해당 서비스 내부에서만 사용하는 메서드라면 private로 만들어줘도 좋을거 같습니다.

2024-04-23 12:24 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/dto/RoomRequestDto.java
> +        private Float latitude;
스웨거를 통해 잘 작성되어있겠지만, 출발지의 위도와 경도 라는것을 명시한다면 더 좋을것 같습니다.
필드명만 보고도 어떤 데이터인지 알 수 있어야할것 같아요.
`CreateRoomRequest.longitude` 라 한다면 명시적이진 않다고 생각합니다.

2024-04-23 12:24 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/service/UpdateRoomService.java
> +            || updateRoomRequest.getLongitude() != null || updateRoomRequest.getLatitude() != null;
프론트에서 잘 사용하면 되겠지만 위도와 경도 둘중 하나의 데이터만 들어오는경우는 핸들링이 필요해보입니다.
지금의 구현으로는 둘중 하나의 값이라도 들어오면 잘못된 데이터로 경로를 산정할것 같네요.

2024-04-23 12:24 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/service/UpdateRoomService.java
> +                : oldRoomData.getLatitude());
위도와 경도 둘중 하나의 데이터만 들어와서 수정이 되는 경우는 제외하는게 맞는것 같습니다.
저희 프론의의 구현도 그렇고 둘중 하나의 데이터만을 가지고 요청을 하는경우는 비정상적인 요청일것입니다.
지도에서 어떤 위치를 지정하여 요청을 보내는 방식이므로 둘중 하나만 있다면 잘못된거겠죠.

2024-04-23 12:49 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/domain/room/dto/RoomResponseDto.java
>                  .duration(room.getDuration())
네 좋아요! 회의 때 얘기하기로 하고 시간이 흐르면서 toDto를 사용하지 않는 쪽으로 진행되고 있는 것 같습니다! 내일 회의 때 확정 지어지면 수정하겠습니다!

2024-04-23 12:53 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/domain/room/service/RegisterRoomService.java
> +
중복 중에서도 정말 굳이굳이 키워드가 붙어야 할 중복코드네요! 수정하겠습니다!

2024-04-23 12:58 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/domain/room/service/UpdateRoomService.java
> +                : oldRoomData.getLatitude());
이것도 팀원 분들 설정이 어떻게 되어있는 지 보고 싶습니다ㅜㅜ 제가 조금 다른 것 같아요

2024-04-23 12:58 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/domain/room/service/UpdateRoomService.java
>      public boolean shouldUpdateTaxiInfo(UpdateRoomRequest updateRoomRequest) {
수정하겠습니다!

2024-04-23 13:12 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/domain/room/service/UpdateRoomService.java
> +                : oldRoomData.getLatitude());
그렇네요! 이와 더불어 수정 로직에 대해서는 create할 때 예외사항에 대해 검증하는 로직을 넣지 않았었네요! 같이 작성해서 push하겠습니다!

2024-04-24 06:33 UTC, YooJisu826 approved these changes
LGTM

2024-04-24 06:33 UTC, YooJisu826 commented on src/main/java/com/modutaxi/api/domain/room/dto/RoomResponseDto.java
> +
단순 궁금인데 뭐가 불편하신건가요(꿍금)

2024-04-24 06:33 UTC, YooJisu826 commented on src/main/java/com/modutaxi/api/domain/room/service/RegisterRoomService.java
> +        createRoomRequestValidator(member, createRoomRequest);
이런거 넘 깔끔하고 좋아요 굿

2024-04-25 10:20 UTC, jaewonLeeKOR approved these changes
LGTM

2024-04-25 11:51 UTC, merged