[MS-119] FCM 구독&메서드 구현
MODU-TAXI/server-api pull request #46
Opened 2024-05-02 11:25 UTC by YooJisu826

## 요약 🎀

- FCM 구독&메서드 구현

## 상세 내용 🌈

- FCM 구독하기
- FCM 메시지 발송 메서드 구현

## 질문 및 이외 사항 🚩

- chatroomId 등의 네이밍은 적절히 바꿔주세요.
- 메서드 안에 파라미터나 data도 적절히 바꿔주세요.

## 리뷰어에게 ✨

- 빨리 원하시는 것 같아서 정성 부족한 PR 죄송합니다..

2024-05-02 14:39 UTC, jaewonLeeKOR reviewed
`firebase-key.json` 파일은 빌드시에 jar파일에 첨부가 되는건가요?
제가 이전에 APNs를 사용했을때는 인증서를 빌드시 함께 복사해줘야 했어서 여쭤봅니다.

2024-05-03 09:00 UTC, YooJisu826 commented
> `firebase-key.json` 파일은 빌드시에 jar파일에 첨부가 되는건가요? 제가 이전에 APNs를 사용했을때는 인증서를 빌드시 함께 복사해줘야 했어서 여쭤봅니다.

제가 돌려보니 바로 적용이 되진 않네요.. 
config에 firebase-key.json을 넣어놨으니 로컬에서 돌리실 땐 config pull 한번 받으시고 resource 파일로 복사 붙여넣기 해주시면 돼요! 디벨롭 빌드할 때는 번거로우시겠지만 따로 넣어서 같이 빌드해주셔야 할 거 같아요 방법이 있을까요?ㅜㅜ

2024-05-03 09:10 UTC, jaewonLeeKOR commented
> > `firebase-key.json` 파일은 빌드시에 jar파일에 첨부가 되는건가요? 제가 이전에 APNs를 사용했을때는 인증서를 빌드시 함께 복사해줘야 했어서 여쭤봅니다.
> 
> 제가 돌려보니 바로 적용이 되진 않네요.. config에 firebase-key.json을 넣어놨으니 로컬에서 돌리실 땐 config pull 한번 받으시고 resource 파일로 복사 붙여넣기 해주시면 돼요! 디벨롭 빌드할 때는 번거로우시겠지만 따로 넣어서 같이 빌드해주셔야 할 거 같아요 방법이 있을까요?ㅜㅜ

그럼 파이어베이스 인증키 참조 로직을 조금 설명 해주시면 제가 배포환경에서 복사하도록 배포 파이프라인을 수정하겠습니다!

2024-05-03 13:18 UTC, tjdgns8439 approved these changes
LGTM!

2024-05-04 08:48 UTC, jaewonLeeKOR requested changes
로그인 시 받은 토큰이 유효한 FCM 토큰인지 확인하는 로직이 필요할거 같아요.
추가적으로 개발 시에는 FCM 토큰을 발급하기 어려우니까 FCM 토큰이 없이 또는 더미 데이터로 로그인할 수 있도록 하는것이 좋을것 같습니다. (FCM 발급을 쉽게 할 수 있는 방법이 있다면 공유해주세요..!)

2024-05-10 08:34 UTC, jaewonLeeKOR approved these changes
GGTV

2024-05-10 08:35 UTC, merged