[MS-128] 채팅로직 FCM 연결
MODU-TAXI/server-api pull request #50
Opened 2024-05-14 15:17 UTC by tjdgns8439

## 요약 🎀
- FCM 연결
- 트랜잭션 관련 트러블 슈팅

## 상세 내용 🌈
**참가, 채팅로직 수정(트랜잭션 범위에 따른 db반영 불일치)**
ex) 방 삭제 시 에러가 난 상황
- 트랜잭션 개념이 적용되지 않는 mongoDB의 경로 정보는 삭제되고, 방정보는 삭제되지 않음.

**FCM - MessageType**
- TEST ( by Token, 요청한 사람 ) `완` - 테스트
- JOIN ( by Topic ) `완` - 채팅방 참여 시
- CHAT ( by Topic ) `완` - 채팅
- LEAVE ( by Topic ) `완` - 채팅방 퇴장 시
- ROOM_UPDATE  ( by Topic ) `완` - 방 정보가 업데이트 되었을 때
- PARTICIPATE_REQUEST ( by Token, 방장에게 ) `완` - 참가요청 들어왔을 때
- MATCHING_COMPLETE ( by Topic ) - 매칭이 완료되어 출발할때
- REMIT_REQUEST ( by Topic ) - 정산요청
- ROOM_DELETE ( by Topic ) `완` - 방 삭제되었을 때
- MATCHING_SUCCESS ( by Token, 수락요청이 된 이에게 ) `완` - 방장이 매칭요청 수락 눌렀을 때
- TIME_TO_DEPART ( by Topic ) - 출발시각
- DEPART_10_MINUTES_AGO ( by Topic ) - 출발시각임박

## 질문 및 이외 사항 🚩
- 작업 하면서 보니 기능들이 필연적이지만 꽤 많은 연관관계가 있음을 깨달았습니다.
그 예시로 글을 삭제할 때 접근해야 하는 로직과 거기에 얽힌 분산데이터가 레디스, RDS, MongoDB 세 개의 DB로 나뉘어져 있었고, 구체적인 사항은 아래와 같았습니다.
- 방 삭제(RDS), 방 경로 삭제(mongoDB), 방 메세지 삭제(mongoDB로 변경 예정), 방 매핑정보 삭제(Redis), 대기열 리스트 삭제(Redis), 참가자리스트삭제(Redis), 채팅 전송(Redis pub/sub), 알림 전송(FCM)
- 문제는 이런 것들이 Cascading 되지 않았고 트랜잭션의 단위가 다르다는 점이었습니다.
- 이에 따라 바로 반영되지 않아도 되고 모아서 한번에 작업할 수 있는 메서드들은 분리하는 것이 트러블 슈팅에도 용이할 것이라 생각했습니다.

**결론**  
▶️▶️▶️ 이에 따라 방을 삭제한 후 해당 방에 접근할 일은 없으니 채팅 내역, 대기열, 참가열 리스트는 스케줄러를 통한 배치작업과 같이 처리하는 것이 좋을 것 같아 기존 로직에서 제거하였습니다.

## 리뷰어에게 ✨
**진행 예정인 작업**
1. API 개발
- 위 FCM에서 완료되지 않은 작업들은 API를 새로 만들어야 합니다. 해당 작업을 진행하겠습니다.
2. 방 정보 반환 시 내가 참여해있는 방인지 여부 반환
3. 채팅 메세지에 이미지 담기
4. 출발임박, 출발시작 등 스케줄러 작업

2024-05-14 15:21 UTC, tjdgns8439 commented
> ## 요약 🎀
> * FCM 연결
> * 트랜잭션 관련 트러블 슈팅
> 
> ## 상세 내용 🌈
> **참가, 채팅로직 수정(트랜잭션 범위에 따른 db반영 불일치)** ex) 방 삭제 시 에러가 난 상황
> 
> * 트랜잭션 개념이 적용되지 않는 mongoDB의 경로 정보는 삭제되고, 방정보는 삭제되지 않음.
> 
> **FCM - MessageType**
> 
> * TEST ( by Token, 요청한 사람 ) `완` - 테스트
> * JOIN ( by Topic ) `완` - 채팅방 참여 시
> * CHAT ( by Topic ) `완` - 채팅
> * LEAVE ( by Topic ) `완` - 채팅방 퇴장 시
> * ROOM_UPDATE  ( by Topic ) `완` - 방 정보가 업데이트 되었을 때
> * PARTICIPATE_REQUEST ( by Token, 방장에게 ) `완` - 참가요청 들어왔을 때
> * MATCHING_COMPLETE ( by Topic ) - 매칭이 완료되어 출발할때
> * REMIT_REQUEST ( by Topic ) - 정산요청
> * ROOM_DELETE ( by Topic ) `완` - 방 삭제되었을 때
> * MATCHING_SUCCESS ( by Token, 수락요청이 된 이에게 ) `완` - 방장이 매칭요청 수락 눌렀을 때
> * TIME_TO_DEPART ( by Topic ) - 출발시각
> * DEPART_10_MINUTES_AGO ( by Topic ) - 출발시각임박
> 
> ## 질문 및 이외 사항 🚩
> * 작업 하면서 보니 기능들이 필연적이지만 꽤 많은 연관관계가 있음을 깨달았습니다.
>   그 예시로 글을 삭제할 때 접근해야 하는 로직과 거기에 얽힌 분산데이터가 레디스, RDS, MongoDB 세 개의 DB로 나뉘어져 있었고, 구체적인 사항은 아래와 같았습니다.
> * 방 삭제(RDS), 방 경로 삭제(mongoDB), 방 메세지 삭제(mongoDB로 변경 예정), 방 매핑정보 삭제(Redis), 대기열 리스트 삭제(Redis), 참가자리스트삭제(Redis), 채팅 전송(Redis pub/sub), 알림 전송(FCM)
> * 문제는 이런 것들이 Cascading 되지 않았고 트랜잭션의 단위가 다르다는 점이었습니다.
> * 이에 따라 바로 반영되지 않아도 되고 모아서 한번에 작업할 수 있는 메서드들은 분리하는 것이 트러블 슈팅에도 용이할 것이라 생각했습니다.
> 
> **결론** ▶️▶️▶️ 이에 따라 방을 삭제한 후 해당 방에 접근할 일은 없으니 채팅 내역, 대기열, 참가열 리스트는 스케줄러를 통한 배치작업과 같이 처리하는 것이 좋을 것 같아 기존 로직에서 제거하였습니다.
> 
> ## 리뷰어에게 ✨
> **진행 예정인 작업**
> 
> 1. API 개발
> 
> * 위 FCM에서 완료되지 않은 작업들은 API를 새로 만들어야 합니다. 해당 작업을 진행하겠습니다.
> 
> 2. 방 정보 반환 시 내가 참여해있는 방인지 여부 반환
> 3. 채팅 메세지에 이미지 담기
> 4. 출발임박, 출발시작 등 스케줄러 작업

++ Fcm이나 웹소켓이나 서버에서 테스트할 방법이 마땅치 않아서 잦은 배포를 해야 했기에 커밋이력이 참 더럽습니다..

2024-05-14 18:01 UTC, YooJisu826 approved these changes
고생하셨습니다아아아아

2024-05-14 18:01 UTC, YooJisu826 commented on src/main/java/com/modutaxi/api/domain/room/mapper/RoomMapper.java
>              .departureDairyDate(TimeFormatConverter.convertTimeToDiaryDate(room.getDepartureTime()))
파라미터로 넘겨받는 `member`가 이 API를 조회한 `member`던데, `managerId`랑 `score`에 `room.getRoomManager()` 것을 넣어야하지 않을까요?!

2024-05-14 18:01 UTC, YooJisu826 commented on src/main/java/com/modutaxi/api/common/exception/errorcode/ChatErrorCode.java
> +    FAIL_FCM_UNSUBSCRIBE("CHAT_008", "FCM 구독취소에 실패했습니다.", HttpStatus.CONFLICT),
우디님이 비슷한 의미 에러는 숫자 붙여주면 좋을 것 같다 했어요! 이번꺼는 나중에 추가한거라 어쩔 수 없지만 담부터라도...!?

2024-05-14 18:01 UTC, YooJisu826 commented on src/main/java/com/modutaxi/api/common/config/websocket/StompHandler.java
> +                    chatRoomMappingInfo.getNickname(),memberId, LocalDateTime.now());
여기 띄어쓰기가 스타일 가이드 적용이 필요할 것 같습니다! 매번 일일이 하기 힘드시죠 ㅜ.ㅜ 저도 save 시 자동으로 가이드 적용되도록 설정해놨는데 편하더라구요!

https://yeon-kr.tistory.com/197 에서 **3. 1) save 시 자동으로 코드 변환** 부분 참고하시면 됩니다!

2024-05-14 18:01 UTC, YooJisu826 commented on src/main/java/com/modutaxi/api/common/fcm/FcmService.java
> +                .putData("content", chatMessageRequestDto.getContent())
Member가 보낸 채팅 내용은 `content`이고, 그 외 정보를 알리는 것은 `message`로 사용하신 것 맞나요?! 단순 질문입니다!

2024-05-14 18:01 UTC, YooJisu826 commented on src/main/java/com/modutaxi/api/common/fcm/FcmService.java
> +    public void sendPermitParticipate(Member participant, String chatroomId) {
그리고 전체적으로 roomId / chatroomId 를 혼용하여 사용하신 것 같은데, 다른건가요? ㅠ `domain > chat`에서 ChatRoom과 Chat이 같이 사용되고 있어서 Chat과 Room이 다른 건 알겠는데 Chatroom도 다른건지 헷갈리네용...!! 혹은 아직 작업 안 하신 부분을 수정하지 않은 것이라고 생각하면 될까요..?!

2024-05-14 18:01 UTC, YooJisu826 commented on src/main/java/com/modutaxi/api/common/fcm/RedisFcmRepositoryImpl.java
> +        classInstance = com.modutaxi.api.common.fcm.RedisFcmRepositoryImpl.class;
마이 미스테이크...... 죄송합니다.... 😱

2024-05-15 11:42 UTC, jaewonLeeKOR requested changes
답변부탁드립니다.

2024-05-15 11:42 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/common/config/websocket/StompHandler.java
>  import org.springframework.stereotype.Component;
`MemberErrorCode`, `ChatMessageService`, `Member`, `Value`, `Authentication` 은 사용하고 있지 않은 요소들인데 import를 지우지 않은 이유가 있나요?

2024-05-15 11:42 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/common/config/websocket/StompHandler.java
> +    private final MemberRepository memberRepository;
`memberRepository`는 여기서 사용하고 있지 않은데 지워도 되지 않을까요

2024-05-15 11:42 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/common/config/websocket/StompHandler.java
> +
진짜 궁금해서 그러는데 없어도 될것같은 개행을 두개를 지우지 않고 두는 이유가 있나요?

2024-05-15 11:42 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/common/config/websocket/StompHandler.java
> +                log.error("이미 연결된 방이 있는데 애꿎은 방을 들어가려고 함");
로그 메세지를 어떤 상황인지를 더 정확히 나타내는것이 좋을거 같습니다.
각자 다른 부분을 개발하고 있으니까 다른 팀원이 로그를 확인해줄때도 어떤 상황인지 더 알아보기 쉬울거 같네요.

2024-05-15 11:42 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/common/fcm/FcmService.java
>              String fcmMessageJson = gson.toJson(message);
여기는 보라가 작업한 부분이네요.
궁금해서 그러는데, 이부분은 객체를 json으로 바꿔주는 부분인가요?
ObejectMapper를 사용해도 되는데 어떤 이유에서 Gson을 사용하는 지 궁금합니다.

2024-05-15 11:42 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/chat/repository/ChatRoomRepository.java
> +    }
저번 PR에서 제대로 확인 못한거 같은데 Redis 의 레포지토리 클래스라고 명시하는게 좋지 않을까요
일전에 훈이 얘기한것처럼 NoSQL 데이터베이스는 트랜잭션이 없기도 하고 RDB와는 다름을 더 명시적이어야할거 같네요.

2024-05-15 11:42 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/chat/service/ChatService.java
>          chatRoomRepository.minusUserCount(chatRoomMappingInfo.getRoomId(), count);
레포지토리에 세번의 요청이 필요한건가요? 이부분은 줄일수가 없을까요?

2024-05-15 11:42 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/service/GetRoomService.java
> +        return RoomMapper.toDto(room, member, path);
Jwt 토큰에 들어있는 정보를 바로 dto로 내보내는거같은데 그럼 managerId가 보내지는거 같지 않습니다.

2024-05-15 11:42 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/mapper/RoomMapper.java
> +            .isMyRoom(room.getRoomManager().getId().equals(member.getId()))
이부분은 자신의 방인지를 검증하는 로직이 아닌거 같습니다. 자신이 해당 방의 장인지를 돌려주는 로직같은데 그를 의도한게 맞나요?

2024-05-15 11:42 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/service/GetRoomService.java
> +import com.modutaxi.api.domain.member.repository.MemberRepository;
`import`문 정리 부탁드립니다.

2024-05-15 11:42 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/service/RegisterRoomService.java
> +import com.modutaxi.api.domain.roomwaiting.service.RoomWaitingService;
`import`문 정리 부탁드립니다.

2024-05-15 11:42 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/domain/room/service/UpdateRoomService.java
> +                        internalUpdateRoomDto.getSpot().getSpotPoint().getY());
어떤 부분이 수정된거죠? 저번에 코드 스타일을 맞춘거 같은데 다시 달라진거 같네요

2024-05-15 15:55 UTC, YooJisu826 commented on src/main/java/com/modutaxi/api/common/fcm/FcmService.java
>              String fcmMessageJson = gson.toJson(message);
여기 그냥 로그 찍으려고 추가한거라 지워도 상관 없는 부분입니다 ㅎㅁㅎ

2024-05-15 16:19 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/domain/room/mapper/RoomMapper.java
> +            .isMyRoom(room.getRoomManager().getId().equals(member.getId()))
프론트 측에서 자기가 만든 방인지 확인해달라고 해서 추가했던 기억이 있습니다.
요청사항을 수동적으로 받아들인 경향이 있기에 이 부분은 매니저 ID만 반환하는 것으로 수정하겠습니다.
추가로 방 리스트를 조회할 때는 자신이 참여한 방인지는 추가해야 할 것 같습니다.
이에 따라 RoomSimpleResponse에 "참여한 방이 맞는지"필드를 추가하겠습니다.

2024-05-15 16:19 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/domain/room/mapper/RoomMapper.java
>              .departureDairyDate(TimeFormatConverter.convertTimeToDiaryDate(room.getDepartureTime()))
예리한 리뷰 감사드립니다..!!!!

2024-05-15 16:19 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/domain/room/service/GetRoomService.java
> +        return RoomMapper.toDto(room, member, path);
감사합니다! 해당 로직은 요청 member를 보내고 toDto 내부에서 보라가 지적해주신 roomManager를 적절하게 찾아오는 것으로 해결했습니다!

2024-05-15 16:19 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/domain/room/service/GetRoomService.java
> +import com.modutaxi.api.domain.member.repository.MemberRepository;
확인했습니다!

2024-05-15 16:19 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/common/fcm/FcmService.java
> +                .putData("content", chatMessageRequestDto.getContent())
이거 message로 통일하겠습니다!

2024-05-15 16:19 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/common/fcm/FcmService.java
> +    public void sendPermitParticipate(Member participant, String chatroomId) {
음~ 코드를 작성하다 보니 조금 스파게티가 된 것 같습니다.
엄밀히 말하면 room과 chatRoom이 같으면서 다릅니다..
room과 chatRoom이 저장되는 db나 정보, 사용하는 로직들이 다르지만 생성, 업데이트, 삭제 등등에서는 room의 로직, chatRoom의 로직들이 한 번에 사용되기도 합니다..ㅜㅜ
그렇기에 어떻게 통일할까 약간 고민되네요..
이 부분은 제가 고민해보고 전체적으로 리팩토링 진행하겠습니다.

2024-05-15 16:19 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/common/fcm/RedisFcmRepositoryImpl.java
> +        classInstance = com.modutaxi.api.common.fcm.RedisFcmRepositoryImpl.class;
아닙니다.. 꼼꼼하게 보지 않은 제.. 잘못..ㅜ

2024-05-15 16:19 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/common/config/websocket/StompHandler.java
>  import org.springframework.stereotype.Component;
import문 정리했습니다ㅜㅜ 죄송합니다

2024-05-15 16:19 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/common/fcm/FcmService.java
>              String fcmMessageJson = gson.toJson(message);
@YooJisu826 보라 태그하겠습니다!

2024-05-15 16:19 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/common/config/websocket/StompHandler.java
> +                log.error("이미 연결된 방이 있는데 애꿎은 방을 들어가려고 함");
더 자세히 추가했습니다!

2024-05-17 02:30 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/common/config/websocket/StompHandler.java
> +                    chatRoomMappingInfo.getNickname(),memberId, LocalDateTime.now());
헉 이거 진짜 꿀팁이네요 감사합니다!

2024-05-19 10:33 UTC, jaewonLeeKOR commented on src/main/java/com/modutaxi/api/common/config/websocket/StompHandler.java
> +                log.error("해당 세션의 사용자는 이미 연결된 방이 있습니다. 애꿎은 방을 들어가려고 하는 상황입니다.");
이 부분이 가시성이 좋은 로그를 위해서 출력하는 부분이라면
"애꿎은"이란 표현보다는 어떤 사용자가 어떤 방에 있는데 어디로 들어가려 한다 를 표현하는게 가시성이 좋을거 같아요.
나중에 로그를 확인할때도 모든 로그가 같게 보이는것보단 정보를 함께 주는게 더 좋다고 생각합니다.
해당 데이터들은 이미 불러온 상태이므로 추가적인 오버헤드는 없을거 같네요.

2024-05-19 14:57 UTC, tjdgns8439 commented on src/main/java/com/modutaxi/api/common/config/websocket/StompHandler.java
> +                log.error("해당 세션의 사용자는 이미 연결된 방이 있습니다. 애꿎은 방을 들어가려고 하는 상황입니다.");
반영하겠습니다.

2024-05-19 15:15 UTC, jaewonLeeKOR approved these changes
LGTM

2024-05-19 15:28 UTC, merged